language: java
sudo: true
jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'

before_install:
  - chmod +x mvnw

script:
  - mvn clean package -DskipTests=true

after_success:
  - echo success!!!

branches:
  only:
    - master

notifications:
  email: false