language: java

jdk:
  - oraclejdk9

cache:
  directories:
    - '$HOME/.m2/repository'

before_script:
  - chmod a+x ./mvnw

script:
  - mvn clean package -DskipTests=true

after_success:
  - echo success!!!

branches:
  only:
    - master

notifications:
  email: false