language: java

jdk:
  - oraclejdk9

cache:
  directories:
    - '$HOME/.m2/repository'

#before_install:
# - chmod +x gradlew

script:
  - mvn clean package -DskipTests=true

after_success:
  - echo success!!!

branches:
  only:
    - master

notifications:
  email: false