spring:
  profiles:
    active: pro
    #active: dev
#  mvc:
#    servlet:
#      path:

server:
  port: 8088

baseUrl:
  img: F:/baseUrl/headImg/

qiniu:
  domain: http://q0de6cmzk.bkt.clouddn.com/

imgPath:
  head: /head/
  blog: /blog/
imgType:
  head: 1
  blog: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    #控制台输出sql语句情况
    map-underscore-to-camel-case: true                       #开启驼峰功能
    jdbc-type-for-null: null                                 #解决插入语句字段为空的报错
  type-aliases-package: com.project.entity                   #指定扫描实体类包，resultType不用加全限定名

pagehelper:

  helper-dialect: mysql        #分页插件方言选择
  reasonable: true             #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
  support-methods-arguments: true

mapper:
  mappers: com.project.config.BaseMapper
  identity: MYSQL

token:
  expire:
    seconds: 3600
