spring:
  profiles:
    active: pro
#  mvc:
#    servlet:
#      path:

server:
  port: 8088

baseUrl:
  img: F:/baseUrl/headImg/

qiniu:
  domain: http://q0de6cmzk.bkt.clouddn.com/

imgPath:
  head: /head/
  blog: /blog/
imgType:
  head: 1
  blog: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    #控制台输出sql语句情况
    map-underscore-to-camel-case: true                       #开启驼峰功能
    jdbc-type-for-null: null                                 #解决插入语句字段为空的报错
  type-aliases-package: com.project.entity                   #指定扫描实体类包，resultType不用加全限定名

pagehelper:

  helper-dialect: mysql        #分页插件方言选择
  reasonable: true             #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
  support-methods-arguments: true

mapper:
  mappers: com.project.config.BaseMapper
  identity: MYSQL

token:
  expire:
    seconds: 3600
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 106.53.223.87:22122
    #- 192.168.188.17:22122
  pool:
    #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: -1
    #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 5000
    #每个key最大连接数
    max-total-per-key: 50
    #每个key对应的连接池最大空闲连接数
    max-idle-per-key: 10
    #每个key对应的连接池最小空闲连接数
    max_idle_per_key: 5