server:
  port: 8087
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 192.168.1.250
    port: 6379


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
  type-aliases-package: com.project.entity

pagehelper:

  helper-dialect: mysql        #分页插件方言选择
  reasonable: true             #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
  support-methods-arguments: true

mapper:
  mappers: com.project.config.BaseMapper
  identity: MYSQL

