server:
  port: 8088

baseUrl:
  img: F:/baseUrl/headImg/


spring:
  devtools:
    restart:
      enabled: false  #设置开启热部署
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 192.168.1.250
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    #控制台输出sql语句情况
    map-underscore-to-camel-case: true                       #开启驼峰功能
    jdbc-type-for-null: null                                 #解决插入语句字段为空的报错
  type-aliases-package: com.project.entity                   #指定扫描实体类包，resultType不用加全限定名

pagehelper:

  helper-dialect: mysql        #分页插件方言选择
  reasonable: true             #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
  support-methods-arguments: true

mapper:
  mappers: com.project.config.BaseMapper
  identity: MYSQL




